name: Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Verify build
        run: |
          if [ "$?" -ne 0 ]; then
            echo "Build failed. Exiting."
            exit 1
          fi
